---
version: "3.7"

services:

  db:
    image: postgres:12
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-drupal}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-drupal}"
      POSTGRES_DB: "${POSTGRES_DB:-drupal}"
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: "docker.io/bitnami/redis:6.0-debian-10"
    restart: always
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD:-drupal}"
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
    #volumes:
    #  - "redis_data:/bitnami/redis/data"
    networks:
      - internal

  drupal:
    image: ${DOCKER_REGISTRY:-docker.tr.utils.nfa.go.ug}/national-forestry-authority/forests:${DRUPAL_IMAGE_TAG:-main}
    #build:
    #  context: .
    depends_on:
      - db
    environment:
      # Overrides Dockerfile defaults
      DB_HOST: db
      DB_DRIVER: pgsql
      DB_PORT: 5432
      PROJECT_BASE_URL: ${HOST_NAME:-}
    restart: unless-stopped
    #ports:
    #  - "${HOST_PORT:-80}:80"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME:-forests}.rule=Host("${HOST_NAME}")
      - com.centurylinklabs.watchtower.monitor-only=true
    volumes:
      - drupal-files:/var/www/web/sites/default/files
      - drupal-private:/var/www/web/private
    networks:
      - internal
      - traefik

volumes:
  db-data:
  drupal-files:
  drupal-private:
  #redis-data:

networks:
  traefik:
    external: true
  internal:
    external: false