site: forests
message: 'Welcome to the NFA Forest Management System to manage forests plans, tracking their implementation and subsequently reporting on the work done through workflows. '
sites:
  farmers:
    name: Farmers
    production: 'https://farmers.nfa.go.ug'
    staging: 'https://farmers.stg.envs.utils.nfa.go.ug'
    development: 'https://farmers.ddev.site'
  forests:
    name: Forests
    production: 'https://forests.nfa.go.ug'
    staging: 'https://forests.stg.envs.utils.nfa.go.ug'
    development: 'https://forests.ddev.site/'
  brms:
    name: BRMS
    production: 'https://brms.nfa.go.ug'
    staging: 'https://brms.stg.envs.utils.nfa.go.ug'
    development: 'https://brms.ddev.site/'
